### ISSUE TITLE
Photo Gallery | Remove subtitles from all photos

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#29]
All photos in the photo gallery currently have ipsum lorem subtitles and need real ones _once the photos have been chosen_ #26.

In the meantime, as agreed below, the task here is to **remove all subtitles for now** and we can deal with them again post-deployment. #27.

<hr/>

@LuchoTurtle Can the current ‘holding’ subtitles be removed relatively simply? And relatively quickly put back?
I ask because it’s the difference between this being an issue that is a blocker for deployment or not #27 

Linked to #21, but not dependent on it.

**Comment by LuchoTurtle** [comment]
You mean the photo gallery that is currently in Services but will eventually have its own page? If you mean the captions that have "example yada yada", sure, they can be removed quite painlessly. 
The Photo Gallery epic is totally dependent on the photos that are to be chosen and how the page will be laid out (I recall people wanting to split the photos by the spaces that we offer). I think this issue is more of a milestone for  #17, where we should focus first.

**Comment by iteles** [comment]
@LuchoTurtle Yes, I mean the photo gallery that will move to its own page.

Totally agree, #17 is a deployment blocker, but we also can't deploy with `example yada yada` as subtitles 😆 

For now I think we should just remove the subtitles for deployment and come back to them post-deployment #27
