### ISSUE TITLE
Events/services section review

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#41]
https://mosteirodelandim.surge.sh/services

This section needs a final review before going live given that we now have a strong lean towards weddings as these are the bread and butter that keeps the place afloat (pretty much).

**Comment by nelsonic** [comment]
What is the total annual *profit* from the weddings? 
Is it enough to cover the maintenance costs of the venue? 
What if the *whole* family didn’t work for free? What if the weddings had to *pay* for the people who put in hundreds of hours per year for “visitas”, customer relations and event management? 
How profitable would it be at the *current* prices? 🤷🏼‍♂️

this doesn’t affect the updating of the content. But it does concern me that the long-term viability is not discussed on family meetings, *ever*.
A venue of this size could be used *far* more effectively especially in the “off season” when there are zero weddings but could easily have other events. 💭

**Comment by iteles** [comment]
The long term viability is certainly discussed and is a conversation for an `hq` repo rather than a website content repo 👍 
Agree that there needs to be a bigger focus on the _off season_ which is the plan after the weddings have been a little more systematised 👌 

Meanwhile, on this, I'm currently editing but will open a secondary issue on photos for this page.

**Comment by iteles** [comment]
## Photo review

Photographers in brackets and we need should credit them in the `alt` text along with the photo description.

Main photo: https://photos.app.goo.gl/XmddyxR7h4TSMGnu5
Jardins: https://photos.app.goo.gl/wC5GhSWSGoSere2i8 (Pedro Marcelino)

Seção onde falsa da cobertura:
Retirar preço e (atenção mudam ligeiramente as legendas):
+ Trocar fotografia que está à esquerda para estar por cima da legenda ‘Montagem de _cobertura_ translúcida’ (Foto de Ana Teresa Miranda) ou, no Limite, esta: https://photos.app.goo.gl/BcRZtEdxxLSWWegQ8
+ Adicionar esta foto onde tens a legenda ‘A cobertura pode ser usada para decoração’:
https://photos.google.com/u/2/album/AF1QipOD_IVTUcU4avMv8-sJAs8c6F8VtWVWUXQi_9-C (As Anas)

Fotos ao fundo da página:
https://photos.app.goo.gl/RdEJX2wue12R66pSA (Conta-me como foi)
https://photos.app.goo.gl/pDtB51JUvFw2P6cs5 (Saiotes)
https://photos.app.goo.gl/zfFEr8x6gLxFb1KAA (Madalena Abreu)
https://photos.app.goo.gl/CJYyNySkuiv2SuSR6 (Pedro Marcelino)
https://photos.app.goo.gl/zQZ61qXuamtWiayn9 (crop à parte de baixo e não a de cima!)

Manter:
+ Sala de estar no claustro
+ Foto pessoas a mesa no claustro com lampadas penduradas
+ Foto dos aperitivos com tomate

**Comment by LuchoTurtle** [comment]
Thanks for the effort @iteles , thoroughly appreciated!
However, I have a few questions:

- **Main photo**: Do you mean the background photo of the title? I think the current one is better not only because it's more aesthetically pleasing but better contrasts the text with the one you suggested.
- **Jardins**: I think the photo with the kid works better, it gives a friendlier vibe to the whole thing.
- **Trocar fotografia da esquerda**: Should we do this? If we switch to the one we mentioned, it features the same decor as in the last picture at the bottom of the page you suggested. 
- **Adicionar esta foto onde tens a legenda ‘A cobertura pode ser usada para decoração’**: link doesn't work.
- **[photos.app.goo.gl/CJYyNySkuiv2SuSR6](https://photos.app.goo.gl/CJYyNySkuiv2SuSR6) (Pedro Marcelino)**: this link isn't a specific picture, it's a folder. Which one should I go for?

Feel free to edit your comment :)

**Comment by iteles** [comment]
Had to add a new comment because I wanted to reply directly to yours :)

+ Main photo: That's the one I mean. Sofia hates the one currently being used  ("as bandeiras são muito folclóricas") and that kind of decor is pretty specific to a certain type of wedding (not the most commonly appealing) which is why we have to change it.
  + I agree the one I've suggested isn't amazing because the lighting is too white which doesn't make it very inviting
  + I'm super happy for you to propose an alternative as it's easier for you to plug in different photos and test with the text overlap
  + If we don't use the one I've suggested for the title, please add it to the photo gallery at the bottom and make it the first photo - this is the photo everyone who has looked on our IG profile mentions so it's an important one!
+ **Jardins:** The photo with the kid doesn't actually show the gardens. Remember our audience for this page is brides, so what we want to show them is all our cool scenery and what an amazing party with friends they can have
+ **Trocar fotografia da esquerda:** You lost me. I'm suggesting that this photo becomes the photo on the left and I don't think this is the same one as any of the ones in the photo gallery?:
<img width="520" alt="image" src="https://user-images.githubusercontent.com/4185328/221730139-9ab85968-021e-4db9-a127-48b0d5072b62.png">

And that we lose this one altogether because it's ugly:
<img width="518" alt="image" src="https://user-images.githubusercontent.com/4185328/221730207-69bfd041-9a3a-48a2-9a3b-3f7b7979e236.png">

+ **Adicionar esta foto onde tens a legenda ‘A cobertura pode ser usada para decoração’:** My bad! This is the one I was referring to: https://photos.google.com/u/2/share/AF1QipP2G1Y7X_kiLaM5ZaOaHlNC4HiyANeP2fdFeaWQ-uChW4rOO5qrclJiTApXkR3p-g/photo/AF1QipO5UBssbK2OXf9DT30UDIhxH6_6wtOT0UR5nTcZ?key=b0VZU1VHQnlBazlLOEtLWUh5YllzWGN4bXVOUTRn
+ **Pedro Marcelino link:** Por exclusão de partes (all the others are in use elsewhere on the page), I think this is the one I meant! https://photos.google.com/share/AF1QipP2G1Y7X_kiLaM5ZaOaHlNC4HiyANeP2fdFeaWQ-uChW4rOO5qrclJiTApXkR3p-g/photo/AF1QipPAog3bX3D0ywKKskffirLB53ptRco9Qt50pv70?key=b0VZU1VHQnlBazlLOEtLWUh5YllzWGN4bXVOUTRn

**Comment by LuchoTurtle** [comment]
@iteles here are the photos that need credits:

![image](https://user-images.githubusercontent.com/17494745/222935523-432d0d5d-3334-4aad-91d9-c77e7cb5d4a0.png)
![image](https://user-images.githubusercontent.com/17494745/222935528-e2a0abef-e6f4-49af-80a4-75e66d62139d.png)
![image](https://user-images.githubusercontent.com/17494745/222935529-6db99361-6527-4b65-bd39-911e543e6253.png)
![image](https://user-images.githubusercontent.com/17494745/222935533-462d0f7d-5c10-4fc6-8582-991e113f8d66.png)
![image](https://user-images.githubusercontent.com/17494745/222935552-555338c3-fa5a-4a73-9034-48917ac663a5.png)

## A few comments

I think these two photos that you chose are not ideal because of their low resolution, which makes it much more noticeable on larger screens. 

![image](https://user-images.githubusercontent.com/17494745/222935561-0ac6e444-f123-4c4b-b007-24f516d4583a.png)
![image](https://user-images.githubusercontent.com/17494745/222935570-9daa13a6-0f18-4ddb-ac80-ce690b42f56e.png)

It's much better to scale down from a high-resolution picture, it looks much crispier. 

Imma leave it up to you though 👍

**Comment by iteles** [comment]
Updated your comment with the photo creds 👍 

On the two photos:

**Image 1**
We must have a compressed version for some reason? Here are the originals, 4.5MP:
https://photos.google.com/u/2/share/AF1QipPvrsuoVKe12Uekd559tPq5bt9d2KO7ZYgDEjas2BYRTLCnmn_tEyev6PhCxL3cZQ/photo/AF1QipP131cKweDHZppoEo1XMr63E4SEQGMAWcDKaSY_

From this album:
https://photos.google.com/u/2/share/AF1QipPvrsuoVKe12Uekd559tPq5bt9d2KO7ZYgDEjas2BYRTLCnmn_tEyev6PhCxL3cZQ

**Image 2**
I can get you a high resolution image of the second one next week.

**Comment by LuchoTurtle** [comment]
Hey @iteles .
Thanks for the answer, those are sorted.
Both links you've sent don't seem to be working :/

I'll wait for those last two images to close this one off! :D

**Comment by iteles** [comment]
@LuchoTurtle Is this link not working for you? https://photos.google.com/u/2/share/AF1QipPvrsuoVKe12Uekd559tPq5bt9d2KO7ZYgDEjas2BYRTLCnmn_tEyev6PhCxL3cZQ

I can't get the other one to work but this one is. I didn't have auto-renewal on for the storage space so access was temporarily blocked.
